### ISSUE TITLE
Mejoras en Card

### ISSUE THREAD

**Issue by hchocobar** [4GeeksAcademy/spain44-g4-landing-page-with-react#10]
En el componente Card, podrian implementar propTypes para realizar una sola tarjeta y recibir los datos como props.
También podrían implementar defaultProps para los casos donde no se envien props al componente.

- [x] Implementar import PropTypes from "prop-types";
- [x] Implementar propTypes
- [x] Implementar defaultProps
- [x] Modificar el componente Home.jsx

**Comment by arroyostack** [comment]
Perfecto, trabajaremos en ello.

**Comment by hchocobar** [comment]
Genial, muchas gracias
